//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class <c>Doctor</c> holds basic informations about doctors.
    /// </summary>
    public partial class Doctor
    {
        /// <summary>
        /// Doctor Id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Doctor's name and surname
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Doctor's specialization
        /// </summary>
        public string Specialization { get; set; }

        /// <summary>
        /// Doctor's qualification
        /// </summary>
        public string Qualification { get; set; }

        /// <summary>
        /// Doctor's age
        /// </summary>
        public Nullable<int> Age { get; set; }
    }
}
