//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
   
    ///<summary>
    /// Class <c>Patient</c> holds basic informations about Patient.
    /// </summary>
    public partial class Patient
    {
        /// <summary>
        /// Id property.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// First name property.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Second name property.
        /// </summary>
        public string SecondName { get; set; }

        /// <summary>
        /// Phone number property.
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Address property
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// Age property
        /// </summary>
        public Nullable<int> Age { get; set; }
    }
}
